name: yolotrain
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cuda-cccl=12.4.127
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.4.127
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - filelock=3.16.1
  - freetype=2.12.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - intel-openmp=2024.2.1
  - jinja2=3.1.4
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.20
  - libffi=3.4.4
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.43
  - libtiff=4.6.0
  - libuv=1.49.2
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.2.13
  - libzlib-wapi=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.4.2
  - numpy=2.1.3
  - openjpeg=2.5.2
  - openssl=3.3.2
  - pillow=10.3.0
  - pip=24.2
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.13.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - albucore==0.0.20
      - albumentations==1.4.21
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - humanfriendly==10.0
      - ipykernel==6.29.5
      - ipython==8.29.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - onnx==1.17.0
      - onnxruntime==1.20.0
      - onnxslim==0.1.36
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - platformdirs==4.3.6
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.3
      - psutil==6.1.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pywin32==308
      - pywinpty==2.0.14
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - simsimd==6.0.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - stringzilla==3.10.9
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.0.2  
      - tornado==6.4.1
      - tqdm==4.66.6
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - tzdata==2024.2
      - ultralytics==8.3.27
      - ultralytics-thop==2.0.10
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13

  - pip:
      - --index-url https://download.pytorch.org/whl/cu118
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1